### ISSUE TITLE
status.nixos.org

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-common-styles#7]
Some time ago we moved https://nixos.org to new design. Ideas is to moved other websites that we host on `nixos.org` domain. 

As https://status.nixos.org/ is simplest of them we are stating with it. All components that are already created in `nixos/nixos-homepage` should be:

1. Moved to this repo
2. Made reusable
3. Document their usage and configuration options via StoryBook

The components that we need for https://status.nixos.org are:
- [x] top site navigation bar (same as on nixos.org, there is no dropdown needed)
- [x] site footer (currently not present on the status.nixos.org, but a footer from nixos.org can be taken for now)
- [x] page title (with optional description)
- [x] table
- [x] alert (warn/info/error/...) the same as defined in bootstrap
- [x] label (warn/info/success/...) the same as defined in bootstrap

**Comment by samueldr** [comment]
As I discussed previously, the `<table>` requires *design work*.

First rough draft. **OBVIOUSLY** the icons are placeholders. Furthermore, I don't think we need an icon for EOL'd channels, but rather we should put them in a second table. Though even in a single table, they should be sunk to the bottom when generating the HTML.

So we'd need an icon to describe "build failures". Something like ⚠ would probably be fine, so I guess the next step would be picking a warning sign up.

Is there anything you don't like with this rough draft, design-wise? Think usage outside of the status page too, for *table* data.

<details>
<summary>Screenshot enclosed</summary>

![image](https://user-images.githubusercontent.com/132835/152272517-0df0408d-b4b5-44b0-be56-bf275abf88af.png)

</details>

**Comment by garbas** [comment]
> Furthermore, I don't think we need an icon for EOL'd channels, but rather we should put them in a second table. Though even in a single table, they should be sunk to the bottom when generating the HTML.
> 

I would agree here, but lets just do the design work for now and we can look at the status.nixos.org and how we can improve the usability of it later.

> So we'd need an icon to describe "build failures". Something like warning would probably be fine, so I guess the next step would be picking a warning sign up.
> 

:+1: I'd let you choose the warning sign.

> Is there anything you don't like with this rough draft, design-wise? Think usage outside of the status page too, for _table_ data.
> 

I like it. Feels like part of nixos.org :)

**Comment by samueldr** [comment]
> I would agree here, but lets just do the design work for now and we can look at the status.nixos.org and how we can improve the usability of it later.

Yep, only brought it up because it *is* related to design considerations, but implementing the *sinking* of EOL'd channels does not block progress.

Thanks for the input, I'll review the implementation in more proper utility classes and that should be basically good.

**Comment by samueldr** [comment]
Here's what I used to test and fake the status page table layout:

 - https://github.com/samueldr/nixos-homepage/commit/ac8c47866c87a3dd75fb9bca163368552cfbf7ba

I replaced the download page with a static copy of the status page DOM, with minimum changes.

**Comment by garbas** [comment]
I think I now have all the components to rebuild status.nixos.org. I'll open issues if something else is needed, but for now I think we can close this issue.
